### test 
GET http://localhost:3000/

### login
GET http://localhost:3000/api/users/login

###qr
GET http://localhost:3000/api/qr/generate

### create user 
POST http://localhost:3000/api/users/create
Content-Type: application/json

{
    "first_name":"ajay",
    "last_name":"singh",
    "type":1
}

### get all user list
GET http://localhost:3000/api/users/get-user

### get single user
GET http://localhost:3000/api/users/detail/1

### create auth token 
POST http://localhost:3000/api/users/token
Content-Type: application/json

{
    "email":"ajaysingh@gmail.com"
}

### create login
POST http://localhost:3000/api/login/signup
Content-Type: application/json

{
    "email":"ajaysingh@gmail.com",
    "password":"x123yx@123"
}

### verify login 
POST http://localhost:3000/api/login/signin
Content-Type: application/json

{
    "email":"ajaysingh@gmail.com",
    "password":"x123yx@123"
}


### getting all login 
GET http://localhost:3000/api/login/get-all
